#!/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

export BASH_USER_CONFIG_PATH="$HOME/.config/bash/bashrc"
export BASH_SYSTEM_CONFIG_PATH="$HOME/.config/bash/bashrc.builtin"

if [ -f "$BASH_SYSTEM_CONFIG_PATH" ]; then
    source "$BASH_SYSTEM_CONFIG_PATH"
fi


if [ -f "$BASH_USER_CONFIG_PATH" ]; then
    source "$BASH_USER_CONFIG_PATH"
fi
