set expandtab " Spaces instead of tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4

set number    " Show line numbers
syntax on     " Turn on syntax highlighting
set ignorecase " Ignore case when searching
set smartcase " Override ignore case if search term contains capital letter
set incsearch " Show search matches as you type
set hlsearch " Highlight search results
set mouse=a " enable mouse in all modes

set directory=~/.vim/swap// " Set swap dir
