#!/bin/bash

if [ -f ~/.config/bash/.bashrc.default ]; then
    source ~/.config/bash/.bashrc.default
fi

if [ -f ~/.config/bash/.bashrc.user ]; then
    source ~/.config/bash/.bashrc.user
fi

source "$HOME/.local/bin/env"
source "$HOME/.cargo/env"
